# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"relpath": "00_core.ipynb",
         "config": "00_core.ipynb",
         "say_hello": "00_core.ipynb",
         "test_model": "00_core.ipynb"}

modules = ["core.py",
           "import_test.py",
           "gpu_tests.py"]

doc_url = "https://none.github.io/nbs/"

git_url = "https://github.com/none/nbs/tree/master/"

def custom_doc_links(name): return None
