# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['config', 'relpath', 'say_hello', 'test_model', 'imshow', 'imread', 'imwrite']

# %% ../00_core.ipynb 3
import sys
import os
def relpath(filepath):
    return os.path.join('../', filepath)
    inJupyter = sys.argv[-1].endswith('json')
    if inJupyter:
        return  os.path.join('../', filepath)
    return filepath

# %% ../00_core.ipynb 4
from dotenv import dotenv_values

config = dict(dotenv_values('../.env'))
config

# %% ../00_core.ipynb 5
def say_hello(to):
    return f'Hi {to}!'

# %% ../00_core.ipynb 7
def test_model():
    return open(relpath("models/test_model.txt"), "r").read()

# %% ../00_core.ipynb 9
def imshow(im):
    from PIL import Image
    import IPython
    return IPython.display.display(Image.fromarray(im))

# %% ../00_core.ipynb 10
import cv2
def imread(path):
    img = cv2.imread(path)
    if len(img.shape) > 2:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img
def imwrite(img, path):
    return cv2.imwrite(path, img)
