# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['config', 'imshow', 'relpath', 'say_hello', 'test_model']

# %% ../00_core.ipynb 3
import sys
import os
def relpath(filepath):
    return os.path.join('../', filepath)
    inJupyter = sys.argv[-1].endswith('json')
    if inJupyter:
        return  os.path.join('../', filepath)
    return filepath

# %% ../00_core.ipynb 4
from dotenv import dotenv_values

config = dict(dotenv_values('../.env'))
config

# %% ../00_core.ipynb 5
def say_hello(to):
    return f'Hi {to}!'

# %% ../00_core.ipynb 7
def test_model():
    return open(relpath("models/test_model.txt"), "r").read()

# %% ../00_core.ipynb 9
import matplotlib.pyplot as plt
import PIL
import IPython

imshow = lambda im: IPython.display.display(PIL.Image.fromarray(im))
