# AUTOGENERATED! DO NOT EDIT! File to edit: src/02_gpu_tests.ipynb (unless otherwise specified).

__all__ = []

# Cell
import torch
f"GPU available: {torch.cuda.is_available()}"

# Cell
import tqdm
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt