# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_gpu_tests.ipynb.

# %% auto 0
__all__ = []

# %% ../02_gpu_tests.ipynb 2
import torch
f"GPU available: {torch.cuda.is_available()}"

# %% ../02_gpu_tests.ipynb 3
import tqdm
import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
