# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_test_utils.ipynb.

# %% auto 0
__all__ = ['test_eq', 'test_fail', 'test_close', 'test_all_notebooks', 'divide', 'test_one_notebook', 'Test']

# %% ../03_test_utils.ipynb 2
import fastcore
from nbdev import test as npdev_test
import numpy as np
from pathlib import Path

# %% ../03_test_utils.ipynb 3
test_eq = fastcore.test.test_eq

# %% ../03_test_utils.ipynb 4
test_fail = fastcore.test.test_fail
def divide(x, y): return x / y

# %% ../03_test_utils.ipynb 5
test_close = fastcore.test.test_close

# %% ../03_test_utils.ipynb 6
def test_one_notebook(notebook_name = '03_test_utils.ipynb'):
    _nb = Path(notebook_name)
    success,duration = npdev_test.test_nb(_nb, force_flags=None, skip_flags=['notest'], do_print=True)
    print(f'success: {success} duration: {duration}')
    
test_all_notebooks = npdev_test.nbdev_test

# %% ../03_test_utils.ipynb 7
class Test:
    def __init__(self, name):
        self.name = name
    
    def __enter__(self):
        pass
    
    def __exit__(self, a, b, c):
        pass
