# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_test_utils.ipynb.

# %% auto 0
__all__ = ['test_eq', 'test_fail', 'divide', 'test_one_notebook', 'test_all_notebooks']

# %% ../03_test_utils.ipynb 2
import fastcore
from nbdev import test as npdev_test
import numpy as np
from pathlib import Path

# %% ../03_test_utils.ipynb 3
test_eq = fastcore.test.test_eq
test_eq('Hammer', 'Hammer')

# %% ../03_test_utils.ipynb 5
test_fail = fastcore.test.test_fail
def divide(x, y): return x / y
test_fail(lambda: divide(1, 0), contains="division by zero")

# %% ../03_test_utils.ipynb 6
def test_one_notebook(notebook_name = '03_test_utils.ipynb'):
    _nb = Path(notebook_name)
    success,duration = npdev_test.test_nb(_nb, skip_flags=['notest'], do_print=True)
    print(f'success: {success} duration: {duration}')
    
def test_all_notebooks():
    npdev_test.nbdev_test()
