definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  default:
    - step:
        name: Build & Test
        image: node:16
        script:
          - npm install -g pnpm
          - pnpm install
          - npm run lint
          - npm run tsc
          - npm run test
        caches:
          - pnpm
          