version: "3.9"
services:
  ex_app:
    platform: "linux/amd64"
    build:
      context: ../../..
      dockerfile: ./apps/example/docker/Dockerfile
    ports:
      - "8060:3000"
    image: ex_app
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://${PG_USER}:${PG_PASSWORD}@postgres:5432/postgres"
    networks:
      main:
        aliases:
          - app
    
  ex_postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./_data/postgres:/data/postgres
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '8051:5432'
    networks:
      main:
        aliases:
          - postgres
    restart: unless-stopped

  # ex_pgadmin:
  #   container_name: fortnox_pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
  #   volumes:
  #     - ./storage/pgadmin:/var/lib/pgadmin
  #   ports:
  #     - '5050:80'
  #   networks:
  #     - main
  #   restart: unless-stopped

networks:
  main:
    driver: bridge
