version: "3.9"
services:
  postgres:
    container_name: example_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./_data/postgres:/data/postgres
    ports:
      - '5432:5432'

networks:
  main:
    driver: bridge
