version: "3.4"
services:
  notebook:
    container_name: ${PROJECT}_nbs
    build:
      context: .
      target: nbs_base
    command: bash -c "cd /repo/src && pip install -e . && jupyter notebook --allow-root --no-browser --ip=0.0.0.0 --port=8080 --NotebookApp.token='' --NotebookApp.password=''"
    ports:
      - "8010:8080"
    volumes:
      - .:/repo/
      - ./data:/data/
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # [GPU:enable] [CPU:disable]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

  server:
    container_name: ${PROJECT}_nbs-server
    build:
      context: .
      target: nbs_base
    command: |
      bash -c "cd /repo/src && pip install -e . && uvicorn server.main:app --host 0.0.0.0 --port 3000 --reload"
    ports:
      - "8006:3000"
    volumes:
      - .:/repo/

# networks:
#   equiferus_main:
#     external: true
